# Generated by Django 5.0.4 on 2024-04-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('bateau', models.CharField(max_length=100)),
                ('capitaine', models.CharField(max_length=100)),
                ('premiereapparition', models.IntegerField(blank=True)),
            ],
        ),
    ]
