# Generated by Django 5.0.4 on 2024-05-12 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepiece', '0002_rename_bateau_equipage_nombateau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipage',
            name='premiereapparition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=100)),
                ('prime', models.IntegerField(blank=True, null=True)),
                ('fruit', models.CharField(blank=True, max_length=100, null=True)),
                ('equipage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onepiece.equipage')),
            ],
        ),
    ]
