# Generated by Django 5.0.4 on 2024-05-13 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepiece', '0003_alter_equipage_premiereapparition_membre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='equipage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='onepiece.equipage'),
        ),
    ]
